In [12]:
# Using Data in countries.csv
# keep the following columns only
#     ['Country','Continent','Population','Area','Coastline','Currency','Birthrate','Deathrate','Life expectancy']]
# change the column names to lowercase
# drop columns with missing values
# limit to countries with populations over 20 million
# reset index to start from zero and count over remaining countries
# add a boolean valued column that is true for countries with coastlines
# Find min and max of the 'life expectancy' for coastl & landlocked countries.
# How many coastal and landlocked countries are in each continent? 
# Determine the mean deathrate for coastal and landlocked countries in each continent.
# Create a new column measuring population density. Determine the mean population density of all the countries. 
# Create a new column 'dense' that is True for countries with higher than average density and False for lower than average density.
# For each category of 'dense' compute the mean birthrate and the difference between the maximal birthrate and the minimal birthrate.

In [13]:
import pandas as pd

In [16]:
df = pd.read_csv("countries.csv", sep=None, engine="python")
df.head()

,Country,Country (de),Country (local),Country code,Continent,Capital,Population,Area,Coastline,Government form,Currency,Currency code,Dialing prefix,Birthrate,Deathrate,Life expectancy,Url
0,Afghanistan,Afghanistan,Afganistan/Afqanestan,AF,Asia,Kabul,33332025,652230,0,Presidential islamic republic,Afghani,AFN,93,38.3,13.7,51.3,https://www.laenderdaten.info/Asien/Afghanista...
1,Egypt,Ägypten,Misr,EG,Africa,Cairo,94666993,1001450,2450,Presidential republic,Pfund,EGP,20,30.3,4.7,72.7,https://www.laenderdaten.info/Afrika/Aegypten/...
2,Åland Islands,Ålandinseln,Åland,AX,Europe,Mariehamn,29013,1580,0,Autonomous region of Finland,Euro,EUR,358,0.0,0.0,0.0,https://www.laenderdaten.info/Europa/Aland/ind...
3,Albania,Albanien,Shqipëria,AL,Europe,Tirana,3038594,28748,362,parliamentary republic,Lek,ALL,355,13.1,6.7,78.3,https://www.laenderdaten.info/Europa/Albanien/...
4,Algeria,Algerien,Al-Jaza’ir/Algérie,DZ,Africa,Algiers,40263711,2381741,998,Presidential republic,Dinar,DZD,213,23.0,4.3,76.8,https://www.laenderdaten.info/Afrika/Algerien/...

In [20]:
# keep the following columns only
#     ['Country','Continent','Population','Area','Coastline','Currency','Birth
df = df[["Country", "Continent", "Population", "Area", "Coastline", "Currency", "Birthrate", "Deathrate", "Life expectancy"]]
df
# change the column names to lowercase
df.columns = df.columns.str.lower()

In [21]:
df

,country,continent,population,area,coastline,currency,birthrate,deathrate,life expectancy
0,Afghanistan,Asia,33332025,652230,0,Afghani,38.3,13.7,51.3
1,Egypt,Africa,94666993,1001450,2450,Pfund,30.3,4.7,72.7
2,Åland Islands,Europe,29013,1580,0,Euro,0.0,0.0,0.0
3,Albania,Europe,3038594,28748,362,Lek,13.1,6.7,78.3
4,Algeria,Africa,40263711,2381741,998,Dinar,23.0,4.3,76.8
...,...,...,...,...,...,...,...,...,...
243,Wallis and Futuna,Oceania,15664,142,129,Franc,13.3,5.2,79.7
244,Christmas Island,Australia,2205,135,139,Dollar,0.0,0.0,0.0
245,Western Sahara,Africa,587020,266000,1110,Dirham,29.8,8.2,63.0
246,Central African Republic,Africa,5507257,622984,0,Franc,34.7,13.5,52.3
247,Cyprus,Asia,1205575,9251,648,Euro,11.4,6.7,78.7

In [22]:
# drop columns with missing values
df = df.dropna(axis=1)

In [ ]:
# limit to countries with populations over 20 million
df = df[df["population"]>20000000]
df = df.loc[df["population"] > 20000000, :]